from .segment_queue_node import (
    NODE_CLASS_MAPPINGS as QUEUE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as QUEUE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .wan_transition_node import SQRWanAnimateTransitionToVideo
from .scail_transition_node import SQRSCAIL2TransitionToVideo
from .scail_reference_nodes import (
    NODE_CLASS_MAPPINGS as SCAIL_REFERENCE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SCAIL_REFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lh_images_folder_loader import (
    NODE_CLASS_MAPPINGS as LH_IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LH_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lh_save_image_passthrough import (
    NODE_CLASS_MAPPINGS as LH_SAVE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LH_SAVE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lh_image_footer_bar import (
    NODE_CLASS_MAPPINGS as LH_FOOTER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LH_FOOTER_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **QUEUE_NODE_CLASS_MAPPINGS,
    **SCAIL_REFERENCE_NODE_CLASS_MAPPINGS,
    **LH_IMAGE_NODE_CLASS_MAPPINGS,
    **LH_SAVE_NODE_CLASS_MAPPINGS,
    **LH_FOOTER_NODE_CLASS_MAPPINGS,
    "SQRWanAnimateTransitionToVideo": SQRWanAnimateTransitionToVideo,
    "SQRSCAIL2TransitionToVideo": SQRSCAIL2TransitionToVideo,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **QUEUE_NODE_DISPLAY_NAME_MAPPINGS,
    **SCAIL_REFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
    **LH_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **LH_SAVE_NODE_DISPLAY_NAME_MAPPINGS,
    **LH_FOOTER_NODE_DISPLAY_NAME_MAPPINGS,
    "SQRWanAnimateTransitionToVideo": "SQR WanAnimate Transition To Video",
    "SQRSCAIL2TransitionToVideo": "SQR SCAIL2 Transition To Video",
}

WEB_DIRECTORY = "./js"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
